// ESLint for the Cloudflare Worker.
//
// The root config globally ignores `workers/**` because its React /
// Vite / browser rules do not apply here — but the effect was that the
// Worker got no linting at all, source included. This config restores it
// with only the parts that make sense for a workerd + Node-tooling
// package: the JS and TypeScript recommended sets, nothing React.
//
// Kept as a sibling config rather than a `files:` block in the root one so
// the two rule sets cannot leak into each other, and so running eslint
// from inside workers/ocr does the right thing on its own.
import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // Generated by `wrangler types` — not ours to lint. Globbed with `**/`
  // rather than a bare relative name: lint-staged invokes eslint from the
  // repo ROOT with `--config`, so a config-relative pattern never matches
  // and a regenerated declaration would block the commit.
  globalIgnores(['**/worker-configuration.d.ts', '**/dist/**']),
  {
    files: ['**/*.ts'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
    ],
    rules: {
      // Same `_`-prefix opt-out as the root config: callbacks that must
      // match a signature they don't fully use say so by naming.
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
      }],
    },
    // No `globals` block: `tseslint.configs.recommended` turns `no-undef`
    // off (TypeScript already resolves globals, and does it per-tsconfig —
    // src and test declare different `types` arrays), so any global list
    // here would be inert and would only look like it was enforcing
    // something. `wrangler types` + the two tsconfigs are the real gate.
    languageOptions: { ecmaVersion: 2024 },
  },
])
