// ESLint for the Cloudflare Worker.
//
// The root config globally ignores `workers/**` because its React /
// Vite / browser rules do not apply here — but the effect was that the
// Worker got no linting at all, source included. This config restores it
// with only the parts that make sense for a workerd + Node-tooling
// package: the JS and TypeScript recommended sets, nothing React.
//
// Kept as a sibling config rather than a `files:` block in the root one so
// the two rule sets cannot leak into each other, and so running eslint
// from inside workers/ocr does the right thing on its own.
import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // Generated by `wrangler types` — not ours to lint.
  globalIgnores(['worker-configuration.d.ts', 'dist']),
  {
    files: ['**/*.ts'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
    ],
    rules: {
      // Same `_`-prefix opt-out as the root config: callbacks that must
      // match a signature they don't fully use say so by naming.
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
      }],
    },
    languageOptions: {
      ecmaVersion: 2024,
      // workerd is neither browser nor Node, but its global surface is
      // much closer to the service-worker one; Node globals are added for
      // the test files, which run under vitest's tooling.
      globals: { ...globals.serviceworker, ...globals.node },
    },
  },
])
